%compile random forest regression by Matlab
%mex CFLAGS="\$CFLAGS -std=c99" -largeArrayDims libsvmread.c
%		mex CFLAGS="\$CFLAGS -std=c99" -largeArrayDims libsvmwrite.c
%		mex CFLAGS="\$CFLAGS -std=c99" -largeArrayDims svmtrain.c ../svm.cpp svm_model_matlab.c

% random forest
mex rf_rgrsn_train.cpp nl_vector.cpp rf_rgrsn_tree_node.cpp rf_rgrsn_tree_cost_function.cpp rf_rgrsn_tree_constant.cpp... 
    rf_rgrsn_constant_regressor.cpp ...
    rf_rgrsn_constant_regressor_builder.cpp

mex rf_rgrsn_predict.cpp nl_vector.cpp rf_rgrsn_tree_node.cpp rf_rgrsn_tree_cost_function.cpp rf_rgrsn_tree_constant.cpp... 
    rf_rgrsn_constant_regressor.cpp ...
    rf_rgrsn_constant_regressor_builder.cpp

% filter forest
%mex ff_rgrsn_train.cpp nl_vector.cpp nl_matrix.cpp...
 %   blas0.cpp blas1_d.cpp linpack_d.cpp lp_least_square.cpp...
  %  ff_tree_cost_function.cpp ff_rgrsn_tree_node.cpp ff_rgrsn_tree.cpp...
  %  ff_rgrsn_regressor.cpp ...
  %  ff_rgrsn_builder.cpp
    

%mex rf_rgrsn_tree_node.cpp
		